apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-code-with-quarkus-7udt
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/mdsaud-tenant/devfile-sample/devfile-sample-code-with-quarkus-7udt@sha256:4ded1ba5504590d8cbab23b0aeba8a3776c07f385cb0b1e7bf1f80d913c0ca8d
        name: my-java-quarkus
        resources: {}
status: {}
